import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Send, Settings, LogOut, Code, Copy, RotateCcw,
  Layout, User, Bot, Monitor, Sparkles, Cloud, ArrowRight
} from 'lucide-react';
import { mockSaveToCloud } from '../firebase';
import './CodeToolPage.css';

const CodeToolPage = () => {
  const navigate = useNavigate();
  const [messages, setMessages] = useState([
    { type: 'bot', content: 'שלום! אני אוואן (Gemini 3). אני כאן כדי לעזור לך ליצור דברים מדהימים.' }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [previewContent, setPreviewContent] = useState(null);
  const [isThinking, setIsThinking] = useState(false);
  const [showAd, setShowAd] = useState(false);
  const [adTimer, setAdTimer] = useState(5);

  // Mock Guest State (In real app, check auth context)
  const isGuest = true;

  // Particles generator
  const particles = Array.from({ length: 20 }).map((_, i) => ({
    id: i,
    left: `${Math.random() * 100}%`,
    animationDuration: `${10 + Math.random() * 20}s`,
    animationDelay: `${Math.random() * 5}s`,
    width: `${5 + Math.random() * 10}px`,
    height: `${5 + Math.random() * 10}px`
  }));

  const handleSendMessage = (e) => {
    e.preventDefault();
    if (!inputMessage.trim()) return;

    const newMessages = [...messages, { type: 'user', content: inputMessage }];
    setMessages(newMessages);
    setInputMessage('');
    setIsThinking(true);

    // Show Ad for guests if requesting code/complex task
    if (isGuest && (inputMessage.includes('קוד') || inputMessage.includes('אתר') || Math.random() > 0.7)) {
      setShowAd(true);
      setAdTimer(5);
    }

    // Simulate Gemini 3 "Thinking" process
    setTimeout(() => {
      let botResponse = { type: 'bot', content: 'מעבד נתונים...' };

      if (inputMessage.includes('קוד') || inputMessage.includes('אתר')) {
        botResponse.content = 'יצרתי עבורך את הקוד המבוקש באמצעות מודל Gemini 3 המתקדם. אנא בדוק את התצוגה המקדימה.';
        setPreviewContent({
          type: 'code',
          code: `
// Generated by Avan (Gemini 3)
function createMagic() {
  const element = document.createElement('div');
  element.style.background = 'linear-gradient(45deg, #ff00cc, #3333ff)';
  element.style.padding = '20px';
  element.style.borderRadius = '10px';
  element.style.color = 'white';
  element.innerHTML = '✨ Magic Happened! ✨';
  document.body.appendChild(element);
}
          `
        });
        mockSaveToCloud({ type: 'code_gen', timestamp: Date.now() });
      } else {
        botResponse.content = 'זו שאלה מצוינת. כמודל שפה מתקדם, אני יכול לנתח את הבקשה שלך ולומר ש... (כאן תבוא תשובה חכמה ומפורטת)';
      }

      setMessages([...newMessages, botResponse]);
      setIsThinking(false);
    }, 3000); // Longer thinking time for "realism"
  };

  useEffect(() => {
    let interval;
    if (showAd && adTimer > 0) {
      interval = setInterval(() => setAdTimer(prev => prev - 1), 1000);
    } else if (adTimer === 0) {
      // Auto close ad after timer? Or keep it open until user closes?
      // Let's keep it open but enable close button
    }
    return () => clearInterval(interval);
  }, [showAd, adTimer]);

  const handleLogout = () => {
    navigate('/');
  };

  return (
    <div className="home-page">
      {/* Particles Background */}
      <div className="particles-container">
        {particles.map(p => (
          <div key={p.id} className="particle" style={{
            left: p.left,
            width: p.width,
            height: p.height,
            animationDuration: p.animationDuration,
            animationDelay: p.animationDelay
          }}></div>
        ))}
      </div>

      {/* Navbar */}
      <nav className="navbar glass-panel">
        <div className="nav-brand">
          <button className="nav-btn" onClick={() => navigate('/home')} style={{ marginLeft: '1rem' }}>
            <ArrowRight size={20} />
          </button>
          <Sparkles size={20} style={{ marginRight: '0.5rem', color: '#ec4899' }} />
          Avan <span style={{ fontSize: '0.8rem', opacity: 0.7, marginLeft: '0.5rem' }}>Code Studio</span>
        </div>
        <div className="nav-actions">
          <button className="nav-btn" title="שמירה בענן" onClick={() => mockSaveToCloud({})}>
            <Cloud size={20} />
          </button>
          <button className="nav-btn" title="הגדרות">
            <Settings size={20} />
          </button>
          <button className="nav-btn" title="התנתקות" onClick={handleLogout}>
            <LogOut size={20} />
          </button>
        </div>
      </nav>

      {/* Main Dashboard */}
      <div className="dashboard-container">

        {/* Left Side: Preview Area */}
        <div className="preview-area">
          {showAd && (
            <div className="ad-overlay">
              <div className="ad-content">
                <div className="ad-badge">פרסומת</div>
                <h2 className="ad-title">שדרג ל-Pro!</h2>
                <p className="ad-text">רוצה לייצר קוד ללא המתנה וללא פרסומות? קבל גישה למודל Gemini 4 Ultra החדש.</p>
                <button className="ad-btn" onClick={() => setShowAd(false)}>
                  {adTimer > 0 ? `אפשר לסגור בעוד ${adTimer}...` : 'סגור פרסומת'}
                </button>
                <div className="ad-timer">Avan Ads System</div>
              </div>
            </div>
          )}

          <div className="preview-header">
            <div className="preview-title">
              <Monitor size={16} />
              תצוגה מקדימה
            </div>
            <div className="preview-actions">
              <button className="action-btn" title="העתק קוד">
                <Copy size={14} /> העתק
              </button>
              <button className="action-btn" title="נסה שוב">
                <RotateCcw size={14} />
              </button>
              <button className="action-btn" title="שינוי פורמט">
                <Layout size={14} />
              </button>
            </div>
          </div>

          <div className="preview-content">
            {isThinking && !showAd ? (
              <div className="empty-state">
                <div className="spinner" style={{
                  width: '40px', height: '40px',
                  border: '4px solid #f3f3f3', borderTop: '4px solid #3b82f6',
                  borderRadius: '50%', animation: 'spin 1s linear infinite'
                }}></div>
                <p>Gemini 3 חושב...</p>
                <style>{`@keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }`}</style>
              </div>
            ) : previewContent ? (
              <pre style={{ textAlign: 'left', direction: 'ltr' }}>
                <code>{previewContent.code}</code>
              </pre>
            ) : (
              <div className="empty-state">
                <Code size={48} />
                <p>הקוד שלך יופיע כאן</p>
              </div>
            )}
          </div>
        </div>

        {/* Right Side: Chat Interface */}
        <div className="chat-interface glass-panel">
          <div className="chat-messages">
            {messages.map((msg, index) => (
              <div key={index} className={`message ${msg.type}`}>
                <div className={`avatar ${msg.type}`}>
                  {msg.type === 'user' ? <User size={20} /> : <Bot size={20} />}
                </div>
                <div className="bubble">
                  {msg.content}
                </div>
              </div>
            ))}
            {isThinking && (
              <div className="message bot">
                <div className="avatar bot"><Bot size={20} /></div>
                <div className="bubble" style={{ opacity: 0.7 }}>...</div>
              </div>
            )}
          </div>

          <div className="chat-input-area">
            <form className="input-wrapper" onSubmit={handleSendMessage}>
              <input
                type="text"
                className="chat-input"
                placeholder="כתוב הודעה ל-Gemini 3..."
                value={inputMessage}
                onChange={(e) => setInputMessage(e.target.value)}
              />
              <button type="submit" className="send-btn">
                <Send size={20} />
              </button>
            </form>
          </div>
        </div>

      </div>
    </div>
  );
};

export default CodeToolPage;
